# baseURL
@baseURL = http://localhost:3001/categories

###
# Find All Categories
GET {{ baseURL }}


###
# Find All Categories
GET {{ baseURL }}/cascader


###
# New Category
POST {{baseURL}}
Content-Type: application/json

{
    "name_uz": "Uz:Category 1-1-3-1-1-1",
    "name_en": "En:Category 1-1-3-1-1-1",
    "name_ru": "En:Category 1-1-3-1-1-1",
    "parent": "/category1/category1-1/category1-1-3/category1-1-3-1/category1-1-3-1-1",
    "category": "/category1/category1-1/category1-1-3/category1-1-3-1-1/category1-1-3-1-1"
}


###
# New Category
POST {{baseURL}}
Content-Type: application/json

{
    "name_uz": "Uz:Category 2-1",
    "name_en": "En:Category 2-1",
    "name_ru": "En:Category 2-1",
    "parent": "/category2",
    "category": "/category2/category2-1"
}



###
# Edit Category
PUT {{baseURL}}
Content-Type: application/json

{
    "_id": "62fa3eb272935538efb14f03",
    "name_uz": "Uz:Category 2-1 edited",
    "name_en": "En:Category 2-1 edited",
    "name_ru": "En:Category 2-1 edited"
}



###
# Delete Category
DELETE {{baseURL}}
Content-Type: application/json

{
    "category": "/category2"
}


###
# Add or remove filter from category
# action is: add or remove
PUT {{baseURL}}/add-or-remove-filter
Content-Type: application/json

{
    "_id": "/cosmetics/decorative",
    "filter_ids": ["634326fc3940ec6d379e8a73"],
    "action": "add"
}